// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Q8c8pB6kBJUFHkq9A7djROWjda4VgM8',
    appId: '1:579284058241:web:7c450ca69ce7f2d9a14d80',
    messagingSenderId: '579284058241',
    projectId: 'how-can-i-make',
    authDomain: 'how-can-i-make.firebaseapp.com',
    storageBucket: 'how-can-i-make.firebasestorage.app',
    measurementId: 'G-615SMMSPMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5mnpHjvicirulsCOsApQj5CZdhAMrkzw',
    appId: '1:579284058241:android:598438955a1ed392a14d80',
    messagingSenderId: '579284058241',
    projectId: 'how-can-i-make',
    storageBucket: 'how-can-i-make.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCez2jBN8l3ynT76x8uW79ZD1U8fcavPvg',
    appId: '1:579284058241:ios:c49b99a8240ba136a14d80',
    messagingSenderId: '579284058241',
    projectId: 'how-can-i-make',
    storageBucket: 'how-can-i-make.firebasestorage.app',
    iosBundleId: 'com.howcanimake.howCanIMake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCez2jBN8l3ynT76x8uW79ZD1U8fcavPvg',
    appId: '1:579284058241:ios:c49b99a8240ba136a14d80',
    messagingSenderId: '579284058241',
    projectId: 'how-can-i-make',
    storageBucket: 'how-can-i-make.firebasestorage.app',
    iosBundleId: 'com.howcanimake.howCanIMake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Q8c8pB6kBJUFHkq9A7djROWjda4VgM8',
    appId: '1:579284058241:web:8adcf380869d8c94a14d80',
    messagingSenderId: '579284058241',
    projectId: 'how-can-i-make',
    authDomain: 'how-can-i-make.firebaseapp.com',
    storageBucket: 'how-can-i-make.firebasestorage.app',
    measurementId: 'G-V9YCPT8FQ3',
  );
}
